apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "0000"
        - name: MYSQL_DATABASE
          value: "rememberv1"
        ports:
        - containerPort: 3306