apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dndzhr/backend:5.0
        env:
        - name: SPRING_DATASOURCE_URL
          # 아래 주소의 mariadb-deploy를 mariadb-service로 변경했습니다.
          value: "jdbc:mariadb://mariadb-service:3306/rememberv1" 
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "0000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8085
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5