apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dndzhr/backend:4.0
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://mariadb-deploy:3306/rememberv1" # DB 서비스 이름과 포트 확인
        - name: SPRING_DATASOURCE_USERNAME
          value: "root" # 실제 DB 사용자명
        - name: SPRING_DATASOURCE_PASSWORD
          value: "0000" # 실제 DB 비밀번호
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8085
        # 컨테이너 안의 애플리케이션이 시작되었는지 확인한다.
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          # 실패를 허용하는 최대 횟수
          failureThreshold: 10
          # 재요청 주기(10초마다 상태를 확인)
          periodSeconds: 10
        # 컨테이너 안의 애플리케이션이 살아있는지 지속적으로 확인한다.
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          # 최초 지연 시간
          initialDelaySeconds: 10
          periodSeconds: 20
        # 컨테이너 안의 애플리케이션이 실제로 서비스 요청에 응답할 수 있는지 확인한다.
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5