apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
stringData:
  # ⚠️ kubectl apply -f 로 직접 적용하세요. GitOps 저장소에는 올리지 마세요!
  DB_USERNAME: "root"
  DB_PASSWORD: "0000"
  JWT_SECRET: "dunoesanchaeg-local-k8s-dev-secret-key-2026-rememberme-SECURE-RANDOM-STRING-FOR-LOCAL-DEPLOYMENT"
  KAKAO_CLIENT_ID: "a3c925bb3ea42d42e7214bbed14cf347"
  KAKAO_ADMIN_KEY: "494a9fd482b8341ce932fa5dd81a6dfd"
  KAKAO_REDIRECT_URI: "http://localhost:30180/kakao-auth"
  KAKAO_CLIENT_SECRET: "sFi1pALMrpS4qpYmeZviK2JQHjpJQkoQ"
  SYSTEM_EMAIL: "junsuk530@gmail.com"
  SYSTEM_EMAIL_PASSWORD: "wpun woul phij nonq"