apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rememberme-frontend
  namespace: argocd 
spec:
  project: default

  source:
    repoURL: git@github.com:heejudy/rememberme.git
    # HEAD 대신 실제 브랜치명인 main을 명시하는 것을 권장합니다.
    targetRevision: main 
    path: k8s/frontend

  destination:
    server: https://kubernetes.default.svc
    # 실제 앱이 배포될 위치는 default가 맞습니다.
    namespace: default 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true